/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import domen.KorisnikEntity;
import javax.swing.JFrame;
import session.Session;

/**
 *
 * @author NEVEN
 */
public class FAdministrator extends javax.swing.JFrame {

    /**
     * Creates new form FAdministrator
     */
    public FAdministrator() {
        initComponents();
        
        setLocationRelativeTo(null);
        upisiUsera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnNoviLet = new javax.swing.JButton();
        jbtnPretraziLet = new javax.swing.JButton();
        jlblUlogovaniKorisnik = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtnNoviLet.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnNoviLet.setText("Novi let");
        jbtnNoviLet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNoviLetActionPerformed(evt);
            }
        });

        jbtnPretraziLet.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnPretraziLet.setText("Pretrazi let");
        jbtnPretraziLet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPretraziLetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlblUlogovaniKorisnik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnNoviLet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnPretraziLet, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jlblUlogovaniKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jbtnNoviLet, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jbtnPretraziLet, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnNoviLetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNoviLetActionPerformed
        JFrame noviLet=new FNoviLet();
        noviLet.setVisible(true);
    }//GEN-LAST:event_jbtnNoviLetActionPerformed

    private void jbtnPretraziLetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPretraziLetActionPerformed
        JFrame pretraziLet=new FIzaberiLet();
        pretraziLet.setVisible(true);
    }//GEN-LAST:event_jbtnPretraziLetActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnNoviLet;
    private javax.swing.JButton jbtnPretraziLet;
    private javax.swing.JLabel jlblUlogovaniKorisnik;
    // End of variables declaration//GEN-END:variables

    private void upisiUsera() {
        KorisnikEntity korisnik=(KorisnikEntity) Session.getInstance().getMap().get("korisnik");
        jlblUlogovaniKorisnik.setText("Ulogovani korisnik: "+ korisnik.getUsername());
    }
}
