/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import controller.Controller;
import domen.GradEntity;
import domen.KompanijaEntity;
import domen.KorisnikEntity;
import domen.LetEntity;
import domen.TipAvionaEntity;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import session.Session;

/**
 *
 * @author NEVEN
 */
public class FNoviLet extends javax.swing.JFrame {

    private LetEntity let;
    private FIzaberiLet p;
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd.MM.yyyy");
    DateTimeFormatter formatterUpdate = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    DateTimeFormatter formatterTime=DateTimeFormatter.ofPattern("HH:mm");
    private Long sifraAktuelnog;
    KorisnikEntity k;
    /**
     * Creates new form FAdministrator
     */
    public FNoviLet() {
        initComponents();
        
        setLocationRelativeTo(null);
        upisiUsera();
        popuniCombo();
        pripremiFormu(FormMode.NEW);
    }

    FNoviLet(Long sifraLeta, FIzaberiLet p) {
        initComponents();
        
        setLocationRelativeTo(null);
        upisiUsera();
        popuniCombo();
        popuniFormu(sifraLeta);
        this.sifraAktuelnog=sifraLeta;
        this.p=p;
        pripremiFormu(FormMode.EDIT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblUlogovaniKorisnik = new javax.swing.JLabel();
        jlblPoruka = new javax.swing.JLabel();
        jbtnKreiraj = new javax.swing.JButton();
        jbtnZapamti = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtxtSifraLeta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtDatumPolaska = new javax.swing.JTextField();
        jtxtVremePolaska = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboGrad = new javax.swing.JComboBox();
        jComboKompanija = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboTipAviona = new javax.swing.JComboBox();
        jbtnSacuvajIzmene = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Let");

        jlblPoruka.setBackground(new java.awt.Color(255, 255, 255));
        jlblPoruka.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbtnKreiraj.setText("Kreiraj let");
        jbtnKreiraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKreirajActionPerformed(evt);
            }
        });

        jbtnZapamti.setText("Zapamti let");
        jbtnZapamti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnZapamtiActionPerformed(evt);
            }
        });

        jLabel1.setText("Sifra leta: ");

        jLabel2.setText("Datum polaska (dd.MM.yyyy): ");

        jLabel3.setText("Vreme polaska (HH:mm): ");

        jLabel4.setText("Grad:");

        jLabel5.setText("Kompanija:");

        jLabel6.setText("Tip aviona:");

        jbtnSacuvajIzmene.setText("Sacuvaj izmene");
        jbtnSacuvajIzmene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajIzmeneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblUlogovaniKorisnik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblPoruka, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtxtSifraLeta, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtxtVremePolaska, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                            .addComponent(jComboGrad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jComboKompanija, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jComboTipAviona, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtxtDatumPolaska, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnSacuvajIzmene)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnKreiraj)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtnZapamti)))
                        .addGap(1, 1, 1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblUlogovaniKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtSifraLeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtDatumPolaska, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtVremePolaska, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboKompanija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboTipAviona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnKreiraj)
                    .addComponent(jbtnZapamti)
                    .addComponent(jbtnSacuvajIzmene))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblPoruka, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnKreirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnKreirajActionPerformed
        try {
            let=new LetEntity();
            jtxtSifraLeta.setText(String.valueOf(Controller.vratiSifruLeta()+1));
            pripremiFormu(FormMode.SAVE);
            jlblPoruka.setText("Sistem je kreirao novi let");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem nije uspeo da kreira let");
        }
    }//GEN-LAST:event_jbtnKreirajActionPerformed

    private void jbtnZapamtiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnZapamtiActionPerformed
        Long sifraLeta=Long.parseLong(jtxtSifraLeta.getText());
        let.setSifraLeta(sifraLeta);
        String datum=jtxtDatumPolaska.getText().trim();
        String vreme=jtxtVremePolaska.getText().trim();
        if(datum.equals("") || vreme.equals("")){
             JOptionPane.showMessageDialog(this, "Sva polja su obavezna");
             return;
        }
        try{
        let.setDatumPolaska(LocalDate.parse(datum, formatter));
        let.setVremePolaska(LocalTime.parse(vreme, formatterTime));
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Format nije dobar");
            return;
        }
        let.setGrad((GradEntity) jComboGrad.getSelectedItem());
        let.setKompanija((KompanijaEntity) jComboKompanija.getSelectedItem());
        let.setTipAviona((TipAvionaEntity) jComboTipAviona.getSelectedItem());
        
        let.setUser(k.getUsername());
        try{
        if(Controller.zapamtiLet(let)){
            JOptionPane.showMessageDialog(rootPane, "Let je sacuvan");
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Let nije sacuvan");
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Dogodila se greska kod cuvanja leta");
        }
    }//GEN-LAST:event_jbtnZapamtiActionPerformed

    private void jbtnSacuvajIzmeneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajIzmeneActionPerformed
        let.setSifraLeta(sifraAktuelnog);
        String datum=jtxtDatumPolaska.getText().trim();
        String vreme=jtxtVremePolaska.getText().trim();
        if(datum.equals("") || vreme.equals("")){
             JOptionPane.showMessageDialog(this, "Sva polja su obavezna");
             return;
        }
        try{
        let.setDatumPolaska(LocalDate.parse(datum, formatterUpdate));
        let.setVremePolaska(LocalTime.parse(vreme, formatterTime));
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Format nije dobar");
            return;
        }
        let.setGrad((GradEntity) jComboGrad.getSelectedItem());
        let.setKompanija((KompanijaEntity) jComboKompanija.getSelectedItem());
        let.setTipAviona((TipAvionaEntity) jComboTipAviona.getSelectedItem());
        let.setUser(k.getUsername());
        try{
        if(Controller.sacuvajIzmeneLet(let)){
            JOptionPane.showMessageDialog(rootPane, "Sacuvane su izmene");
            p.osveziFormu();
            dispose();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Izmene nisu sacuvane");
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Dogodila se greska kod cuvanja izmena leta");
        }
    }//GEN-LAST:event_jbtnSacuvajIzmeneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboGrad;
    private javax.swing.JComboBox jComboKompanija;
    private javax.swing.JComboBox jComboTipAviona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jbtnKreiraj;
    private javax.swing.JButton jbtnSacuvajIzmene;
    private javax.swing.JButton jbtnZapamti;
    private javax.swing.JLabel jlblPoruka;
    private javax.swing.JLabel jlblUlogovaniKorisnik;
    private javax.swing.JTextField jtxtDatumPolaska;
    private javax.swing.JTextField jtxtSifraLeta;
    private javax.swing.JTextField jtxtVremePolaska;
    // End of variables declaration//GEN-END:variables

    private void upisiUsera() {
        k=(KorisnikEntity) Session.getInstance().getMap().get("korisnik");
        jlblUlogovaniKorisnik.setText("Ulogovani korisnik: "+ k.getUsername());
    }

    private void popuniCombo() {
        try {
            List<GradEntity> gradovi = Controller.vratiSveGradove();
            List<KompanijaEntity> kompanije=Controller.vratiSveKompanije();
            List<TipAvionaEntity> tipovi=Controller.vratiSveTipove();
            
            jComboGrad.removeAllItems();
            jComboTipAviona.removeAllItems();
            jComboKompanija.removeAllItems();
            
        for (GradEntity grad : gradovi) {
            jComboGrad.addItem(grad);
        }
        
        for (TipAvionaEntity tipAviona : tipovi) {
            jComboTipAviona.addItem(tipAviona);
        }
        
        for (KompanijaEntity kompanija : kompanije) {
            jComboKompanija.addItem(kompanija);
        }
        } catch (Exception ex) {
            Logger.getLogger(FNoviLet.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void popuniFormu(Long sifraLeta){
        try {
            LetEntity letL=Controller.vratiLet(sifraLeta);
            
            jtxtSifraLeta.setText(String.valueOf(letL.getSifraLeta()));
            jtxtDatumPolaska.setText(String.valueOf(letL.getDatumPolaska()));
            jtxtVremePolaska.setText(String.valueOf(letL.getVremePolaska()));
            jComboGrad.setSelectedItem(letL.getGrad());
            jComboKompanija.setSelectedItem(letL.getKompanija());
            jComboTipAviona.setSelectedItem(letL.getTipAviona());
            
            this.let=letL;
            jtxtSifraLeta.setEditable(false);
        } catch (Exception ex) {
            Logger.getLogger(FNoviLet.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void pripremiFormu(FormMode mode){
        switch(mode){
            case NEW:
                jbtnSacuvajIzmene.setVisible(false);
                jbtnKreiraj.setVisible(true);
                jbtnZapamti.setVisible(false);
                
                jtxtSifraLeta.setEditable(false);
                jtxtDatumPolaska.setEditable(false);
                jtxtVremePolaska.setEditable(false);
                
                jComboGrad.setEnabled(false);
                jComboKompanija.setEnabled(false);
                jComboTipAviona.setEnabled(false);
                break;
            case SAVE:
                jbtnSacuvajIzmene.setVisible(false);
                jbtnKreiraj.setVisible(false);
                jbtnZapamti.setVisible(true);
                
                jtxtSifraLeta.setEditable(false);
                jtxtDatumPolaska.setEditable(true);
                jtxtVremePolaska.setEditable(true);
                
                jComboGrad.setEnabled(true);
                jComboKompanija.setEnabled(true);
                jComboTipAviona.setEnabled(true);
                break;
            case EDIT:
                jbtnSacuvajIzmene.setVisible(true);
                jbtnKreiraj.setVisible(false);
                jbtnZapamti.setVisible(false);
                
                jtxtSifraLeta.setEditable(false);
                jtxtDatumPolaska.setEditable(true);
                jtxtVremePolaska.setEditable(true);
                
                jComboGrad.setEnabled(true);
                jComboKompanija.setEnabled(true);
                jComboTipAviona.setEnabled(true);
                break;
        }
    }
}
