/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import controller.Controller;
import domen.KorisnikEntity;
import domen.PutnikEntity;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import session.Session;

/**
 *
 * @author NEVEN
 */
public class FNoviPutnik extends javax.swing.JDialog {

    private FIzaberiPutnika glavna;
    private PutnikEntity putnik;
    KorisnikEntity k;
    /**
     * Creates new form FNoviPutnik
     */
    public FNoviPutnik(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        setLocationRelativeTo(null);
        pripremiFormu(FormMode.NEW);
        k=(KorisnikEntity) Session.getInstance().getMap().get("korisnik");
    }

    FNoviPutnik(java.awt.Frame parent, boolean modal, FIzaberiPutnika i) {
        super(parent, modal);
        initComponents();
        
        setLocationRelativeTo(null);
        glavna=i;
        pripremiFormu(FormMode.NEW);
        k=(KorisnikEntity) Session.getInstance().getMap().get("korisnik");
    }
    
    FNoviPutnik(java.awt.Frame parent, boolean modal, FIzaberiPutnika i,Long sifra) {
        super(parent, modal);
        initComponents();
        
        setLocationRelativeTo(null);
        glavna=i;
        popuniFormu(sifra);
        pripremiFormu(FormMode.EDIT);
        k=(KorisnikEntity) Session.getInstance().getMap().get("korisnik");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtSifraPutnika = new javax.swing.JTextField();
        jtxtIme = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtPrezime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtJMBG = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtTelefon = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jbtnKreiraj = new javax.swing.JButton();
        jbtnZapamti = new javax.swing.JButton();
        jbtnSacuvajIzmene = new javax.swing.JButton();
        jlblPoruka = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novi putnik");

        jLabel1.setText("sifra putnika:");

        jLabel2.setText("Ime:");

        jLabel3.setText("Prezime:");

        jLabel4.setText("JMBG:");

        jLabel5.setText("Telefon:");

        jbtnKreiraj.setText("Kreiraj");
        jbtnKreiraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKreirajActionPerformed(evt);
            }
        });

        jbtnZapamti.setText("Zapamti");
        jbtnZapamti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnZapamtiActionPerformed(evt);
            }
        });

        jbtnSacuvajIzmene.setText("Sacuvaj izmene");
        jbtnSacuvajIzmene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajIzmeneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jlblPoruka, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnSacuvajIzmene)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnKreiraj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnZapamti))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(48, 48, 48)
                        .addComponent(jtxtSifraPutnika, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtSifraPutnika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnKreiraj)
                        .addComponent(jbtnSacuvajIzmene))
                    .addComponent(jbtnZapamti, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblPoruka, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnKreirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnKreirajActionPerformed
        try {
            putnik=new PutnikEntity();
            jtxtSifraPutnika.setText(String.valueOf(Controller.vratiSifruPutnika()+1));
            jtxtSifraPutnika.setEditable(false);
            pripremiFormu(FormMode.SAVE);
            jlblPoruka.setText("Sistem je kreirao novog putnika");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "sistem ne moze da kreira novog putnika");
        }
    }//GEN-LAST:event_jbtnKreirajActionPerformed

    private void jbtnZapamtiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnZapamtiActionPerformed
        Long sifraPutnika=Long.parseLong(jtxtSifraPutnika.getText());
        putnik.setSifraPutnika(sifraPutnika);
        putnik.setIme(jtxtIme.getText().trim());
        putnik.setPrezime(jtxtPrezime.getText().trim());
        putnik.setJmbg(jtxtJMBG.getText().trim());
        putnik.setTelefon(jtxtTelefon.getText().trim());
        if(putnik.getIme().equals("") || putnik.getPrezime().equals("")
                || putnik.getJmbg().equals("") || putnik.getTelefon().equals("")){
            JOptionPane.showMessageDialog(null, "Sva polja su obavezna");
            return;
        }
        putnik.setUser(k.getUsername());
        try{
        if(Controller.zapamtiPutnika(putnik)){
            JOptionPane.showMessageDialog(rootPane, "Putnik je sacuvan");
            this.dispose();
            
        }else{
            JOptionPane.showMessageDialog(rootPane, "Putnik nije sacuvan");
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Dogodila se greska kod cuvanja putnika");
        }
    }//GEN-LAST:event_jbtnZapamtiActionPerformed

    private void jbtnSacuvajIzmeneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajIzmeneActionPerformed
        putnik.setSifraPutnika(Long.parseLong(jtxtSifraPutnika.getText()));
        putnik.setIme(jtxtIme.getText().trim());
        putnik.setPrezime(jtxtPrezime.getText().trim());
        putnik.setJmbg(jtxtJMBG.getText().trim());
        putnik.setTelefon(jtxtTelefon.getText().trim());
        putnik.setUser(k.getUsername());
        try{
        if(Controller.sacuvajIzmenePutnik(putnik)){
            JOptionPane.showMessageDialog(rootPane, "Sacuvane su izmene");
            glavna.osveziTabelu();
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Izmene nisu sacuvane");
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Dogodila se greska kod cuvanja izmena putnika");
        }
    }//GEN-LAST:event_jbtnSacuvajIzmeneActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbtnKreiraj;
    private javax.swing.JButton jbtnSacuvajIzmene;
    private javax.swing.JButton jbtnZapamti;
    private javax.swing.JLabel jlblPoruka;
    private javax.swing.JTextField jtxtIme;
    private javax.swing.JTextField jtxtJMBG;
    private javax.swing.JTextField jtxtPrezime;
    private javax.swing.JTextField jtxtSifraPutnika;
    private javax.swing.JTextField jtxtTelefon;
    // End of variables declaration//GEN-END:variables

    private void popuniFormu(Long sifra) {
        try {
            PutnikEntity putnikP=Controller.vratiPutnika(sifra);
            
            jtxtSifraPutnika.setText(String.valueOf(putnikP.getSifraPutnika()));
            jtxtIme.setText(putnikP.getIme());
            jtxtPrezime.setText(putnikP.getPrezime());
            jtxtJMBG.setText(putnikP.getJmbg());
            jtxtTelefon.setText(putnikP.getTelefon());
            
            this.putnik=putnikP;
            jtxtSifraPutnika.setEditable(false);
        } catch (Exception ex) {
            Logger.getLogger(FNoviLet.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void pripremiFormu(FormMode mode) {
        switch(mode){
            case NEW:
                jbtnSacuvajIzmene.setVisible(false);
                jbtnKreiraj.setVisible(true);
                jbtnZapamti.setVisible(false);
                
                jtxtSifraPutnika.setEditable(false);
                jtxtIme.setEditable(false);
                jtxtPrezime.setEditable(false);
                jtxtJMBG.setEditable(false);
                jtxtTelefon.setEditable(false);
                break;
            case SAVE:
                jbtnSacuvajIzmene.setVisible(false);
                jbtnKreiraj.setVisible(false);
                jbtnZapamti.setVisible(true);
                
                jtxtSifraPutnika.setEditable(false);
                jtxtIme.setEditable(true);
                jtxtPrezime.setEditable(true);
                jtxtJMBG.setEditable(true);
                jtxtTelefon.setEditable(true);
                break;
            case EDIT:
                jbtnSacuvajIzmene.setVisible(true);
                jbtnKreiraj.setVisible(false);
                jbtnZapamti.setVisible(false);
                
                jtxtSifraPutnika.setEditable(false);
                jtxtIme.setEditable(true);
                jtxtPrezime.setEditable(true);
                jtxtJMBG.setEditable(true);
                jtxtTelefon.setEditable(true);
                break;
        }
    }
}
