/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import domen.KorisnikEntity;
import javax.swing.JDialog;
import javax.swing.JFrame;
import session.Session;

/**
 *
 * @author NEVEN
 */
public class FRadnik extends javax.swing.JFrame {

    /**
     * Creates new form FRadnik
     */
    public FRadnik() {
        initComponents();
        setLocationRelativeTo(null);
        upisiUsera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnUnosRezervacije = new javax.swing.JButton();
        jbtnPretragaRezervacije = new javax.swing.JButton();
        jbtnUnosRadnika = new javax.swing.JButton();
        jbtnPretragaRadnika = new javax.swing.JButton();
        jlblUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Radnik");

        jbtnUnosRezervacije.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnUnosRezervacije.setText("Unos rezervacije");
        jbtnUnosRezervacije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUnosRezervacijeActionPerformed(evt);
            }
        });

        jbtnPretragaRezervacije.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnPretragaRezervacije.setText("Pretraga rezervacije");
        jbtnPretragaRezervacije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPretragaRezervacijeActionPerformed(evt);
            }
        });

        jbtnUnosRadnika.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnUnosRadnika.setText("Unos putnika");
        jbtnUnosRadnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUnosRadnikaActionPerformed(evt);
            }
        });

        jbtnPretragaRadnika.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnPretragaRadnika.setText("Pretraga putnika");
        jbtnPretragaRadnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPretragaRadnikaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlblUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(jbtnPretragaRezervacije, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jbtnPretragaRadnika, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jbtnUnosRezervacije, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jbtnUnosRadnika, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jlblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnUnosRezervacije, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnUnosRadnika, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnPretragaRadnika, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnPretragaRezervacije, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnUnosRezervacijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUnosRezervacijeActionPerformed
        JFrame unosRez=new FNovaRezervacija();
        unosRez.setVisible(true);
    }//GEN-LAST:event_jbtnUnosRezervacijeActionPerformed

    private void jbtnPretragaRezervacijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPretragaRezervacijeActionPerformed
        JFrame pretragaRez=new FIzaberiRezervaciju();
        pretragaRez.setVisible(true);
    }//GEN-LAST:event_jbtnPretragaRezervacijeActionPerformed

    private void jbtnUnosRadnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUnosRadnikaActionPerformed
        JDialog unosPutnika=new FNoviPutnik(this, true);
        unosPutnika.setVisible(true);
    }//GEN-LAST:event_jbtnUnosRadnikaActionPerformed

    private void jbtnPretragaRadnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPretragaRadnikaActionPerformed
        JFrame pretragaPutnika=new FIzaberiPutnika();
        pretragaPutnika.setVisible(true);
    }//GEN-LAST:event_jbtnPretragaRadnikaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnPretragaRadnika;
    private javax.swing.JButton jbtnPretragaRezervacije;
    private javax.swing.JButton jbtnUnosRadnika;
    private javax.swing.JButton jbtnUnosRezervacije;
    private javax.swing.JLabel jlblUser;
    // End of variables declaration//GEN-END:variables

    private void upisiUsera() {
        KorisnikEntity korisnik=(KorisnikEntity) Session.getInstance().getMap().get("korisnik");
        jlblUser.setText("Ulogovani korisnik: "+ korisnik.getUsername());
    }
}
